url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "ODAP | Outbreak Data Analysis Platform" # the name of your site, e.g. ACME Corp.
tagline: "Facilitating biomedical research to advance understanding of disease."
description: >- # this means to ignore newlines until "baseurl:"
 The ODAP exists to facilitate biomedical research to advance understanding of disease caused by emerging or re-emerging pathogens (new infectious agents, and new, re-emerging or therapy-resistant forms of existing infectious agents) or other exposures (new or unexplained poisoning, or exposure to harmful energy sources such as electromagnetic radiation) of public health interest. Research within the ODAP is strictly limited to this purpose.
email: odap@ed.ac.uk
author: 
twitter:
  username: 
  card: summary #keep this to generate a twitter share card

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
#  - jekyll-autoprefixer
